#!/bin/bash

ver=0.10

echo "kot-pkg ver $ver"
echo "by TheOrangeCat"

if [[ $EUID = 0 ]]
then
    echo "kot-pkg mustn't be run with root or sudo"
    exit 1
fi

pathtoself=$(dirname $0)

echo "Updating pkglist..."

wget -q https://raw.githubusercontent.com/TheOrangeCat/kot-pkg/master/repo/pkglist -O $pathtoself/pkglist

option=$1
pkg=$2
addopt=$3
echo "Checking package availability..."

case $option in
    install)
        if [[ $(ls $path | grep $pkg) != "" ]]
        then
            case $addopt in
                "--force-inst")
                    echo "WARNING: $pkg is installed, but the --force-inst flag is set."
                    echo "DO NOT reinstall packages unless you know what you're doing."
                    echo "Continue?[y/n]"
                    read forceinstconfirm
                    case $forceinstconfirm in
                        y)
                        ;;
                        *)
                        exit 1
                        ;;
                    esac
                    ;;
                 *)
                    echo "$pkg is already installed"
                    exit 1
                    ;;
              esac
        fi
        if [[ $(cat $pathtoself/pkglist | grep $pkg) = "" ]]
        then
            echo "Package not found. Exiting..."
            exit 1
        else
            echo "Package found. Installing..."
            mkdir $pathtoself/pkg-temp
            wget -q https://raw.githubusercontent.com/TheOrangeCat/kot-pkg/master/repo/$pkg/installpkg.sh -O $pathtoself/pkg-temp/inst.sh
            bash $pathtoself/pkg-temp/inst.sh $pathtoself/pkgs
            rm -rf $pathtoself/pkg-temp/
            echo "Installation complete. Thank you for using kot-pkg!"
        fi
        ;;
    remove)
        if [[ $(ls $pathtoself/pkgs | grep $pkg) = "" ]]
        then
            echo "$pkg is not installed, or might be out of kot-pkg's reach."
            exit 1
        fi
        echo "Removing $pkg..."
        bash $pathtoself/pkgs/"$pkg".d/rmpkg.sh $pathtoself/pkgs/"$pkg".d/
        ;;
    selfupdate)
        echo "Self-updating..."
        wget -q https://raw.githubusercontent.com/TheOrangeCat/kot-pkg/master/subroutines/selfupdate.sh -O $pathtoself/subroutines/selfupdate.sh
        bash $pathtoself/subroutines/selfupdate.sh $pathtoself
        echo "Done."
        ;;
    help)
        echo "Usage: kot-pkg {install|selfupdate|help|remove} [package]"
        echo "install - install a package"
        echo "selfupdate - update kot-pkg and it's subroutines"
        echo "help - display this menu"
        ;;
    *)
        echo "You set a wrong option, or I haven't written it yet :)"
        exit 1
        ;;
esac
