#!/bin/bash

ver=0.05

echo "kot-pkg ver $ver"
echo "by TheOrangeCat"

if [[ $EUID = 0 ]]
then
    echo "kot-pkg mustn't be run with root or sudo"
    exit 1
fi

pathtoself=$(dirname $0)

echo "Updating pkglist..."

wget -q https://raw.githubusercontent.com/TheOrangeCat/kot-pkg/master/repo/pkglist -O $pathtoself/pkglist

option=$1
pkg=$2

echo "Checking package availability..."

case $option in
    install)
        if [[ $(ls /bin | grep $pkg) != "" && $(ls /sbin | grep $pkg) != "" && $(ls /usr/bin | grep $pkg) != "" && $(ls /usr/sbin | grep $pkg) != "" && $(ls $pathtoself/pkgs | grep $pkg) ]] ;
        then
            echo "$pkg is already installed"
            exit 1
        fi
        if [[ $(cat $pathtoself/pkglist | grep $pkg) = "" ]]
        then
            echo "Package not found. Exiting..."
            exit 1
        else
            echo "Package found. Installing..."
            mkdir $pathtoself/pkg-temp
            wget -q https://raw.githubusercontent.com/TheOrangeCat/kot-pkg/master/repo/$pkg/installpkg.sh -O $pathtoself/pkg-temp/inst.sh
            bash $pathtoself/pkg-temp/inst.sh $pathtoself/pkgs
            rm -rf $pathtoself/pkg-temp/
            echo "Installation complete. Thank you for using kot-pkg!"
        fi
        ;;
    selfupdate)
        echo "Self-updating..."
        bash $pathtoself/selfupdate.sh
        echo "Done."
        ;;
    *)
        echo "You set a wrong option, or I haven't written it yet :)"
        exit 1
        ;;
esac
